# Generated by Django 3.2 on 2024-09-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_products_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItme',
            new_name='CartItem',
        ),
    ]
