# Generated by Django 3.2 on 2024-09-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_cartitme_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
    ]
